response = client.batch_write_item(
RequestItems={
    'producer':[
{'PutRequest':
         {'Item':
             {'name':
                 {'S':'facebook'}
             }
         }
     },
     {'PutRequest':
          {'Item':
              {'name':
                  {'S':'amazon'}
              }
          }
     },
     {'PutRequest':
          {'Item':
              {'name':
                  {'S':'netflix'}
              }
          }
     },
    {'PutRequest':
          {'Item':
              {'name':
                  {'S':'google'}
              }
          }
     },
    {'PutRequest':
          {'Item':
              {'name':
                  {'S':'microsoft'}
              }
          }
     },
     {'PutRequest':
          {'Item':
              {'name':
                  {'S':'spotify'}
              }
          }
     },
     {'PutRequest':
          {'Item':
              {'name':
                  {'S':'nvidia'}
              }
          }
     },
     {'PutRequest':
          {'Item':
              {'name':
                  {'S':'ibm'}
              }
          }
     },
     {'PutRequest':
          {'Item':
              {'name':
                  {'S':'oracle'}
              }
          }
     }
     ]
     }
     )